FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY WeatherApi.com.csproj WeatherApi.com.csproj
RUN dotnet restore WeatherApi.com.csproj
COPY . .
WORKDIR /src
RUN dotnet build WeatherApi.com.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish WeatherApi.com.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WeatherApi.com.dll"]